import React from 'react';
import { Header } from '..';
import Head from 'next/head';
import Footer from '../common/Footer';

function Layout({ children }) {
  return (
    <div className="h-screen ">
      <Head>
        <title>cryptvise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Lexend+Giga:wght@200;300;400&display=swap"
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header />
      {children}
      {/* <Footer /> */}
    </div>
  );
}

export default Layout;
