import { useState, useEffect } from 'react';
import { AboutUs, Header, PreLoader, Services, World } from '../components';
import Hero from '../components/Hero/Hero';
import Layout from '../components/Layout';
import Head from 'next/head';
import Footer from '../components/common/Footer';
import { AnimateSharedLayout } from 'framer-motion';

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);
  const delay = 5;

  useEffect(() => {
    let timer1 = setTimeout(() => setIsLoading(false), delay * 1000);

    return () => {
      clearTimeout(timer1);
    };
  }, []);
  return (
    <>
      <Head>
        <title>cryptvise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Lexend+Giga:wght@200;300;400&display=swap"
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <AnimateSharedLayout>
        {isLoading && <PreLoader />}
        <Header />
        <Hero />
        <World />
        <Services />
        <AboutUs />
        <Footer />
      </AnimateSharedLayout>
    </>
  );
}
